{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "visionplus-bss-auth",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.1.1.aar",
          "url": "visionplus-bss-auth-1.1.1.aar",
          "size": 1371328,
          "sha512": "23df0c2cbfcf52239c44e405681be7c0ab9b4ea27a78d1e109d8cd4e395c33878fe3673ee16719b7d199e41765ad5545c1892b9f90a3f34f861afeb28857ad7b",
          "sha256": "077ce40ef58f999c7102c66afff8033772f3bd83e5a5658310da5c64710e8803",
          "sha1": "47b2a16ce78b93eaa121b0ec9e36e77377c60cf3",
          "md5": "7257df1c88f772485e508d72304a5a1d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.7.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.1.1.aar",
          "url": "visionplus-bss-auth-1.1.1.aar",
          "size": 1371328,
          "sha512": "23df0c2cbfcf52239c44e405681be7c0ab9b4ea27a78d1e109d8cd4e395c33878fe3673ee16719b7d199e41765ad5545c1892b9f90a3f34f861afeb28857ad7b",
          "sha256": "077ce40ef58f999c7102c66afff8033772f3bd83e5a5658310da5c64710e8803",
          "sha1": "47b2a16ce78b93eaa121b0ec9e36e77377c60cf3",
          "md5": "7257df1c88f772485e508d72304a5a1d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "visionplus-bss-auth-1.1.1-sources.jar",
          "url": "visionplus-bss-auth-1.1.1-sources.jar",
          "size": 140877,
          "sha512": "75cd8548194d99b3a9959760ef0121cb7269941f9536972fb31254836cb3399dee088571dd487fa1c0d4a0055a7db599e3c56e2b8c67338ec0148ac0a82961d3",
          "sha256": "e564e19ddd6dc85a8c0ba22a2ab8daf3b32e3e4b6d1640662d030461f13ff2f4",
          "sha1": "ab6dbc00a0062b8a05d29828a45c5257455fc646",
          "md5": "c7737da28e0de2b70219d1b2c03d8bd3"
        }
      ]
    }
  ]
}
