{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "visionplus-bss-auth",
    "version": "1.8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.2.1.aar",
          "url": "visionplus-bss-auth-1.8.2.1.aar",
          "size": 1956226,
          "sha512": "046c64f81a01f213699703d1f99729e2908c31509c2c5cc683307b23e13b8bdd327052b4fcc4ceea513d51964594ccf3fb28e9822c664aa60a21b236aaa40dfd",
          "sha256": "9997eab224205ed7d1dea8a49666188f9a7217c9cd19a477def0390a9693c559",
          "sha1": "7557618e93434ad3e8a7dc1318152b755b9b2a32",
          "md5": "722f94f64737a40b80607af5599536e9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.05.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.google.android.recaptcha",
          "module": "recaptcha",
          "version": {
            "requires": "18.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.2.1.aar",
          "url": "visionplus-bss-auth-1.8.2.1.aar",
          "size": 1956226,
          "sha512": "046c64f81a01f213699703d1f99729e2908c31509c2c5cc683307b23e13b8bdd327052b4fcc4ceea513d51964594ccf3fb28e9822c664aa60a21b236aaa40dfd",
          "sha256": "9997eab224205ed7d1dea8a49666188f9a7217c9cd19a477def0390a9693c559",
          "sha1": "7557618e93434ad3e8a7dc1318152b755b9b2a32",
          "md5": "722f94f64737a40b80607af5599536e9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.2.1-sources.jar",
          "url": "visionplus-bss-auth-1.8.2.1-sources.jar",
          "size": 227575,
          "sha512": "7f834fb3a3aecca5c74df5efa3a6bc8a064cbb619b3955c0f66359e28798dbb35e7d75a4d099109dba90ecb76f487588bb4477810af04be599be27968c3e3306",
          "sha256": "e6b4ae9c8d78c76c43b5e832dba3644fcde527773416eb9aa3f24d7ce5fda905",
          "sha1": "463b016a361f8cf4a99a46c4ffb479857060ad38",
          "md5": "5c8bf19b37194519ca657c98fd570aea"
        }
      ]
    }
  ]
}
