{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "visionplus-bss-auth",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.2.1.aar",
          "url": "visionplus-bss-auth-1.2.1.aar",
          "size": 1370729,
          "sha512": "bed8ecb19206220fc65ef8dac82239fac3b073bfb3cdb2aaf4b51ce7fa1b9c48673c74568f8067e9ad366a7c063c19e1e18f46ef02c9694342129635d1afaa24",
          "sha256": "47364432dccce7831dbb56ee6b02d864ad51e543838ba8ecb61ec7da0ac8d484",
          "sha1": "e42e7253f099f51ee705d1a0d01c13afdc257c72",
          "md5": "ffedc7d0a40755b5c7ff5c3e391210ca"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.7.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.2.1.aar",
          "url": "visionplus-bss-auth-1.2.1.aar",
          "size": 1370729,
          "sha512": "bed8ecb19206220fc65ef8dac82239fac3b073bfb3cdb2aaf4b51ce7fa1b9c48673c74568f8067e9ad366a7c063c19e1e18f46ef02c9694342129635d1afaa24",
          "sha256": "47364432dccce7831dbb56ee6b02d864ad51e543838ba8ecb61ec7da0ac8d484",
          "sha1": "e42e7253f099f51ee705d1a0d01c13afdc257c72",
          "md5": "ffedc7d0a40755b5c7ff5c3e391210ca"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "visionplus-bss-auth-1.2.1-sources.jar",
          "url": "visionplus-bss-auth-1.2.1-sources.jar",
          "size": 140795,
          "sha512": "1fbae781785ae0f38f107a031383242a2531aa0d0ee5d188bc14fd43c61456741cccc94082403afbfd0a45bb1a5e56c0dcdb945f198727eb49040a0ba7d6a818",
          "sha256": "db958be4b3d1a0b9c0f766ae23f1beb9d49ac7f55503607d2232305fdec7844b",
          "sha1": "457c24fd47d4a080902d0087b047d90befa46d76",
          "md5": "3f0e4e55b656a0391251434edf6120cb"
        }
      ]
    }
  ]
}
