{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "visionplus-bss-auth",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.0.aar",
          "url": "visionplus-bss-auth-1.8.0.aar",
          "size": 1681605,
          "sha512": "15d4d3f5ad94427232b90e4db8f5a4c95f3ba9b76c2117c9bd83174b761e5bbf769234c16e9ebcce31ddee5a9d65a1c174acadf9b37a476510dc5054a54d65b8",
          "sha256": "dac89d3ed78970f9d12f97c8df7cc5cd2bf46fa59e2f49244f34e0b439ca3379",
          "sha1": "ed16e03eea692bb0bd2037c3f883f1bf074b6d70",
          "md5": "5087f8459e961cabcb68712195d41c0a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.recaptcha",
          "module": "recaptcha",
          "version": {
            "requires": "18.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "18.0.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.0.aar",
          "url": "visionplus-bss-auth-1.8.0.aar",
          "size": 1681605,
          "sha512": "15d4d3f5ad94427232b90e4db8f5a4c95f3ba9b76c2117c9bd83174b761e5bbf769234c16e9ebcce31ddee5a9d65a1c174acadf9b37a476510dc5054a54d65b8",
          "sha256": "dac89d3ed78970f9d12f97c8df7cc5cd2bf46fa59e2f49244f34e0b439ca3379",
          "sha1": "ed16e03eea692bb0bd2037c3f883f1bf074b6d70",
          "md5": "5087f8459e961cabcb68712195d41c0a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "visionplus-bss-auth-1.8.0-sources.jar",
          "url": "visionplus-bss-auth-1.8.0-sources.jar",
          "size": 227443,
          "sha512": "1b0e5cf746437600d2a8afd6caf685ee1eecd8803b545b34b96465b4a39c3e9d0f003616e17a25d56bf959060f19bd14510088cce1bf7f47ee0015b0a940bbed",
          "sha256": "b3b31c30025121b6802d513b6b480ed2fc9deb1751b27fb7173ae84bd3c6a45d",
          "sha1": "a44bf03f536091baf33b30eaa1b2117dbb0e6282",
          "md5": "bf54aa7b7c76b78b8bc5826346f2cd89"
        }
      ]
    }
  ]
}
