{
  "formatVersion": "1.1",
  "component": {
    "group": "id.visionplus",
    "module": "visionplus-bss-auth",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.9.1.aar",
          "url": "visionplus-bss-auth-1.9.1.aar",
          "size": 2088726,
          "sha512": "d16265af32d40198d69ab043d5888cb8c8501f5ab7f68655d8bcfaec02fea86abce4a2e5f3701fdb0199a1dc3193d545745d26350bbda11ba2e6cd5e4c49cdb9",
          "sha256": "946f384f5084a6851ddedf26ea3c3d0ae1394c0a29f26319427a9c0818ca8007",
          "sha1": "e80a55718f06f8a583fc2e7b5bfdf028be0580b8",
          "md5": "a21c35b21ba438d900be6b2717533436"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-firestore"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.google.android.recaptcha",
          "module": "recaptcha",
          "version": {
            "requires": "18.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "visionplus-bss-auth-1.9.1.aar",
          "url": "visionplus-bss-auth-1.9.1.aar",
          "size": 2088726,
          "sha512": "d16265af32d40198d69ab043d5888cb8c8501f5ab7f68655d8bcfaec02fea86abce4a2e5f3701fdb0199a1dc3193d545745d26350bbda11ba2e6cd5e4c49cdb9",
          "sha256": "946f384f5084a6851ddedf26ea3c3d0ae1394c0a29f26319427a9c0818ca8007",
          "sha1": "e80a55718f06f8a583fc2e7b5bfdf028be0580b8",
          "md5": "a21c35b21ba438d900be6b2717533436"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "visionplus-bss-auth-1.9.1-sources.jar",
          "url": "visionplus-bss-auth-1.9.1-sources.jar",
          "size": 256747,
          "sha512": "27328bd1f8de2f82aafb8003fd46cfda113aba5d4fab39af2b6a9a0064a3f538c60390ef84f322ad3ddc4c1981ad7b7d5eecf1dfc7a6074570840148abee7ae1",
          "sha256": "c2912c84309e89ffbcac35ce905d1347be87ac1ea221a4a399515447ef65a5d1",
          "sha1": "6e38f014e96517b00e9608aca5af76cce6de65f1",
          "md5": "2a4727a9e447e21d179b34600019fcde"
        }
      ]
    }
  ]
}
